// Generated by gencpp from file testing_package/Land.msg
// DO NOT EDIT!


#ifndef TESTING_PACKAGE_MESSAGE_LAND_H
#define TESTING_PACKAGE_MESSAGE_LAND_H

#include <ros/service_traits.h>


#include <testing_package/LandRequest.h>
#include <testing_package/LandResponse.h>


namespace testing_package
{

struct Land
{

typedef LandRequest Request;
typedef LandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Land
} // namespace testing_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testing_package::Land > {
  static const char* value()
  {
    return "22c7c465d64c7e74c6ae22029c7ca150";
  }

  static const char* value(const ::testing_package::Land&) { return value(); }
};

template<>
struct DataType< ::testing_package::Land > {
  static const char* value()
  {
    return "testing_package/Land";
  }

  static const char* value(const ::testing_package::Land&) { return value(); }
};


// service_traits::MD5Sum< ::testing_package::LandRequest> should match
// service_traits::MD5Sum< ::testing_package::Land >
template<>
struct MD5Sum< ::testing_package::LandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testing_package::Land >::value();
  }
  static const char* value(const ::testing_package::LandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_package::LandRequest> should match
// service_traits::DataType< ::testing_package::Land >
template<>
struct DataType< ::testing_package::LandRequest>
{
  static const char* value()
  {
    return DataType< ::testing_package::Land >::value();
  }
  static const char* value(const ::testing_package::LandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testing_package::LandResponse> should match
// service_traits::MD5Sum< ::testing_package::Land >
template<>
struct MD5Sum< ::testing_package::LandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testing_package::Land >::value();
  }
  static const char* value(const ::testing_package::LandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_package::LandResponse> should match
// service_traits::DataType< ::testing_package::Land >
template<>
struct DataType< ::testing_package::LandResponse>
{
  static const char* value()
  {
    return DataType< ::testing_package::Land >::value();
  }
  static const char* value(const ::testing_package::LandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTING_PACKAGE_MESSAGE_LAND_H
