// Generated by gencpp from file testing_package/LandRequest.msg
// DO NOT EDIT!


#ifndef TESTING_PACKAGE_MESSAGE_LANDREQUEST_H
#define TESTING_PACKAGE_MESSAGE_LANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace testing_package
{
template <class ContainerAllocator>
struct LandRequest_
{
  typedef LandRequest_<ContainerAllocator> Type;

  LandRequest_()
    : command()  {
    }
  LandRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::testing_package::LandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testing_package::LandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LandRequest_

typedef ::testing_package::LandRequest_<std::allocator<void> > LandRequest;

typedef boost::shared_ptr< ::testing_package::LandRequest > LandRequestPtr;
typedef boost::shared_ptr< ::testing_package::LandRequest const> LandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testing_package::LandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testing_package::LandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::testing_package::LandRequest_<ContainerAllocator1> & lhs, const ::testing_package::LandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::testing_package::LandRequest_<ContainerAllocator1> & lhs, const ::testing_package::LandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace testing_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::testing_package::LandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testing_package::LandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testing_package::LandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testing_package::LandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testing_package::LandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testing_package::LandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testing_package::LandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::testing_package::LandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::testing_package::LandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testing_package/LandRequest";
  }

  static const char* value(const ::testing_package::LandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testing_package::LandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string    command\n"
;
  }

  static const char* value(const ::testing_package::LandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testing_package::LandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testing_package::LandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::testing_package::LandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTING_PACKAGE_MESSAGE_LANDREQUEST_H
