// Generated by gencpp from file testing_package/modifyText.msg
// DO NOT EDIT!


#ifndef TESTING_PACKAGE_MESSAGE_MODIFYTEXT_H
#define TESTING_PACKAGE_MESSAGE_MODIFYTEXT_H

#include <ros/service_traits.h>


#include <testing_package/modifyTextRequest.h>
#include <testing_package/modifyTextResponse.h>


namespace testing_package
{

struct modifyText
{

typedef modifyTextRequest Request;
typedef modifyTextResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct modifyText
} // namespace testing_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testing_package::modifyText > {
  static const char* value()
  {
    return "2ea50b9bce33ae6fad63d90c193917b0";
  }

  static const char* value(const ::testing_package::modifyText&) { return value(); }
};

template<>
struct DataType< ::testing_package::modifyText > {
  static const char* value()
  {
    return "testing_package/modifyText";
  }

  static const char* value(const ::testing_package::modifyText&) { return value(); }
};


// service_traits::MD5Sum< ::testing_package::modifyTextRequest> should match
// service_traits::MD5Sum< ::testing_package::modifyText >
template<>
struct MD5Sum< ::testing_package::modifyTextRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testing_package::modifyText >::value();
  }
  static const char* value(const ::testing_package::modifyTextRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_package::modifyTextRequest> should match
// service_traits::DataType< ::testing_package::modifyText >
template<>
struct DataType< ::testing_package::modifyTextRequest>
{
  static const char* value()
  {
    return DataType< ::testing_package::modifyText >::value();
  }
  static const char* value(const ::testing_package::modifyTextRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testing_package::modifyTextResponse> should match
// service_traits::MD5Sum< ::testing_package::modifyText >
template<>
struct MD5Sum< ::testing_package::modifyTextResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testing_package::modifyText >::value();
  }
  static const char* value(const ::testing_package::modifyTextResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_package::modifyTextResponse> should match
// service_traits::DataType< ::testing_package::modifyText >
template<>
struct DataType< ::testing_package::modifyTextResponse>
{
  static const char* value()
  {
    return DataType< ::testing_package::modifyText >::value();
  }
  static const char* value(const ::testing_package::modifyTextResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTING_PACKAGE_MESSAGE_MODIFYTEXT_H
